version: '3'
services:
  merkle-guard-server:
    container_name: local-merkle-guard-server
    build:
      context: ../../
      dockerfile: deploy/local/Dockerfile.server
    networks:
      - merkle-guard-net
    ports:
      - "50051:50051"
    environment:
      SERVER_ADDRESS: merkle-guard-server:50051
      MERKLE_ROOT_FILE: merkleroot.txt
      FILE_PREFIX: file
      FILE_FORMAT: .txt 

  merkle-guard-client:
    container_name: local-merkle-guard-client 
    build:
      context: ../../
      dockerfile: deploy/local/Dockerfile.client
    networks:
      - merkle-guard-net
    environment:
      SERVER_ADDRESS: merkle-guard-server:50051
      MERKLE_ROOT_FILE: merkleroot.txt
      FILE_PREFIX: file
      FILE_FORMAT: .txt  
    depends_on:
      - merkle-guard-server

networks:
  merkle-guard-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16 

